### ISSUE TITLE
トップページページのタイトル重複問題

### ISSUE THREAD

**Issue by mpkato** [sigirtokyo/sigirtokyo.github.io#1]
現在トップページのタイトルが「ACM SIGIR 東京支部 - ACM SIGIR 東京支部」となっているようです．直そうと思ったのですが，もしかして，themes以下のフォルダを更新していたりされていますでしょうか？ちょっと下手に触るのが怖くなったのでとりあえずissueを立てました．

**Comment by yegusa** [comment]
@masao  さーん，調べてくださーい。

**Comment by mpkato** [comment]
16ce68e で解決しました！
